;;;
;;; this file should be `Index.lisp' and reside in the directory containing the
;;; tsdb(1) test suite skeleton databases (typically a subdirectory `skeletons'
;;; in the tsdb(1) database root directory `*tsdb-home*').

(
 ((:path . "tanaka_ja_0")   (:content . "Tanaka Corpus Ja Set 0 (dev)"))
 ((:path . "tanaka_ja_1")   (:content . "Tanaka Corpus Ja Set 1 (dev)"))
  ((:path . "tanaka_ja_10") (:content . "Tanaka Corpus Ja Set 10"))
  ((:path . "tanaka_ja_100") (:content . "Tanaka Corpus Ja Set 100"))
  ((:path . "tanaka_ja_101") (:content . "Tanaka Corpus Ja Set 101"))
  ((:path . "tanaka_ja_102") (:content . "Tanaka Corpus Ja Set 102"))
  ((:path . "tanaka_ja_103") (:content . "Tanaka Corpus Ja Set 103"))
  ((:path . "tanaka_ja_104") (:content . "Tanaka Corpus Ja Set 104"))
  ((:path . "tanaka_ja_11") (:content . "Tanaka Corpus Ja Set 11"))
  ((:path . "tanaka_ja_12") (:content . "Tanaka Corpus Ja Set 12"))
  ((:path . "tanaka_ja_13") (:content . "Tanaka Corpus Ja Set 13"))
  ((:path . "tanaka_ja_14") (:content . "Tanaka Corpus Ja Set 14"))
  ((:path . "tanaka_ja_15") (:content . "Tanaka Corpus Ja Set 15"))
  ((:path . "tanaka_ja_16") (:content . "Tanaka Corpus Ja Set 16"))
  ((:path . "tanaka_ja_17") (:content . "Tanaka Corpus Ja Set 17"))
  ((:path . "tanaka_ja_18") (:content . "Tanaka Corpus Ja Set 18"))
  ((:path . "tanaka_ja_19") (:content . "Tanaka Corpus Ja Set 19"))
  ((:path . "tanaka_ja_2")  (:content . "Tanaka Corpus Ja Set 2 (dev)"))
  ((:path . "tanaka_ja_20") (:content . "Tanaka Corpus Ja Set 20"))
  ((:path . "tanaka_ja_21") (:content . "Tanaka Corpus Ja Set 21"))
  ((:path . "tanaka_ja_22") (:content . "Tanaka Corpus Ja Set 22"))
  ((:path . "tanaka_ja_23") (:content . "Tanaka Corpus Ja Set 23"))
  ((:path . "tanaka_ja_24") (:content . "Tanaka Corpus Ja Set 24"))
  ((:path . "tanaka_ja_25") (:content . "Tanaka Corpus Ja Set 25"))
  ((:path . "tanaka_ja_26") (:content . "Tanaka Corpus Ja Set 26"))
  ((:path . "tanaka_ja_27") (:content . "Tanaka Corpus Ja Set 27"))
  ((:path . "tanaka_ja_28") (:content . "Tanaka Corpus Ja Set 28"))
  ((:path . "tanaka_ja_29") (:content . "Tanaka Corpus Ja Set 29"))
  ((:path . "tanaka_ja_3")  (:content . "Tanaka Corpus Ja Set 3 (test)"))
  ((:path . "tanaka_ja_30") (:content . "Tanaka Corpus Ja Set 30"))
  ((:path . "tanaka_ja_31") (:content . "Tanaka Corpus Ja Set 31"))
  ((:path . "tanaka_ja_32") (:content . "Tanaka Corpus Ja Set 32"))
  ((:path . "tanaka_ja_33") (:content . "Tanaka Corpus Ja Set 33"))
  ((:path . "tanaka_ja_34") (:content . "Tanaka Corpus Ja Set 34"))
  ((:path . "tanaka_ja_35") (:content . "Tanaka Corpus Ja Set 35"))
  ((:path . "tanaka_ja_36") (:content . "Tanaka Corpus Ja Set 36"))
  ((:path . "tanaka_ja_37") (:content . "Tanaka Corpus Ja Set 37"))
  ((:path . "tanaka_ja_38") (:content . "Tanaka Corpus Ja Set 38"))
  ((:path . "tanaka_ja_39") (:content . "Tanaka Corpus Ja Set 39"))
  ((:path . "tanaka_ja_4")  (:content . "Tanaka Corpus Ja Set 4 (test)"))
  ((:path . "tanaka_ja_40") (:content . "Tanaka Corpus Ja Set 40"))
  ((:path . "tanaka_ja_41") (:content . "Tanaka Corpus Ja Set 41"))
  ((:path . "tanaka_ja_42") (:content . "Tanaka Corpus Ja Set 42"))
  ((:path . "tanaka_ja_43") (:content . "Tanaka Corpus Ja Set 43"))
  ((:path . "tanaka_ja_44") (:content . "Tanaka Corpus Ja Set 44"))
  ((:path . "tanaka_ja_45") (:content . "Tanaka Corpus Ja Set 45"))
  ((:path . "tanaka_ja_46") (:content . "Tanaka Corpus Ja Set 46"))
  ((:path . "tanaka_ja_47") (:content . "Tanaka Corpus Ja Set 47"))
  ((:path . "tanaka_ja_48") (:content . "Tanaka Corpus Ja Set 48"))
  ((:path . "tanaka_ja_49") (:content . "Tanaka Corpus Ja Set 49"))
  ((:path . "tanaka_ja_5")  (:content . "Tanaka Corpus Ja Set 5 (test)"))
  ((:path . "tanaka_ja_50") (:content . "Tanaka Corpus Ja Set 50"))
  ((:path . "tanaka_ja_51") (:content . "Tanaka Corpus Ja Set 51"))
  ((:path . "tanaka_ja_52") (:content . "Tanaka Corpus Ja Set 52"))
  ((:path . "tanaka_ja_53") (:content . "Tanaka Corpus Ja Set 53"))
  ((:path . "tanaka_ja_54") (:content . "Tanaka Corpus Ja Set 54"))
  ((:path . "tanaka_ja_55") (:content . "Tanaka Corpus Ja Set 55"))
  ((:path . "tanaka_ja_56") (:content . "Tanaka Corpus Ja Set 56"))
  ((:path . "tanaka_ja_57") (:content . "Tanaka Corpus Ja Set 57"))
  ((:path . "tanaka_ja_58") (:content . "Tanaka Corpus Ja Set 58"))
  ((:path . "tanaka_ja_59") (:content . "Tanaka Corpus Ja Set 59"))
  ((:path . "tanaka_ja_6") (:content . "Tanaka Corpus Ja Set 6"))
  ((:path . "tanaka_ja_60") (:content . "Tanaka Corpus Ja Set 60"))
  ((:path . "tanaka_ja_61") (:content . "Tanaka Corpus Ja Set 61"))
  ((:path . "tanaka_ja_62") (:content . "Tanaka Corpus Ja Set 62"))
  ((:path . "tanaka_ja_63") (:content . "Tanaka Corpus Ja Set 63"))
  ((:path . "tanaka_ja_64") (:content . "Tanaka Corpus Ja Set 64"))
  ((:path . "tanaka_ja_65") (:content . "Tanaka Corpus Ja Set 65"))
  ((:path . "tanaka_ja_66") (:content . "Tanaka Corpus Ja Set 66"))
  ((:path . "tanaka_ja_67") (:content . "Tanaka Corpus Ja Set 67"))
  ((:path . "tanaka_ja_68") (:content . "Tanaka Corpus Ja Set 68"))
  ((:path . "tanaka_ja_69") (:content . "Tanaka Corpus Ja Set 69"))
  ((:path . "tanaka_ja_7") (:content . "Tanaka Corpus Ja Set 7"))
  ((:path . "tanaka_ja_70") (:content . "Tanaka Corpus Ja Set 70"))
  ((:path . "tanaka_ja_71") (:content . "Tanaka Corpus Ja Set 71"))
  ((:path . "tanaka_ja_72") (:content . "Tanaka Corpus Ja Set 72"))
  ((:path . "tanaka_ja_73") (:content . "Tanaka Corpus Ja Set 73"))
  ((:path . "tanaka_ja_74") (:content . "Tanaka Corpus Ja Set 74"))
  ((:path . "tanaka_ja_75") (:content . "Tanaka Corpus Ja Set 75"))
  ((:path . "tanaka_ja_76") (:content . "Tanaka Corpus Ja Set 76"))
  ((:path . "tanaka_ja_77") (:content . "Tanaka Corpus Ja Set 77"))
  ((:path . "tanaka_ja_78") (:content . "Tanaka Corpus Ja Set 78"))
  ((:path . "tanaka_ja_79") (:content . "Tanaka Corpus Ja Set 79"))
  ((:path . "tanaka_ja_8") (:content . "Tanaka Corpus Ja Set 8"))
  ((:path . "tanaka_ja_80") (:content . "Tanaka Corpus Ja Set 80"))
  ((:path . "tanaka_ja_81") (:content . "Tanaka Corpus Ja Set 81"))
  ((:path . "tanaka_ja_82") (:content . "Tanaka Corpus Ja Set 82"))
  ((:path . "tanaka_ja_83") (:content . "Tanaka Corpus Ja Set 83"))
  ((:path . "tanaka_ja_84") (:content . "Tanaka Corpus Ja Set 84"))
  ((:path . "tanaka_ja_85") (:content . "Tanaka Corpus Ja Set 85"))
  ((:path . "tanaka_ja_86") (:content . "Tanaka Corpus Ja Set 86"))
  ((:path . "tanaka_ja_87") (:content . "Tanaka Corpus Ja Set 87"))
  ((:path . "tanaka_ja_88") (:content . "Tanaka Corpus Ja Set 88"))
  ((:path . "tanaka_ja_89") (:content . "Tanaka Corpus Ja Set 89"))
  ((:path . "tanaka_ja_9") (:content . "Tanaka Corpus Ja Set 9"))
  ((:path . "tanaka_ja_90") (:content . "Tanaka Corpus Ja Set 90"))
  ((:path . "tanaka_ja_91") (:content . "Tanaka Corpus Ja Set 91"))
  ((:path . "tanaka_ja_92") (:content . "Tanaka Corpus Ja Set 92"))
  ((:path . "tanaka_ja_93") (:content . "Tanaka Corpus Ja Set 93"))
  ((:path . "tanaka_ja_94") (:content . "Tanaka Corpus Ja Set 94"))
  ((:path . "tanaka_ja_95") (:content . "Tanaka Corpus Ja Set 95"))
  ((:path . "tanaka_ja_96") (:content . "Tanaka Corpus Ja Set 96"))
  ((:path . "tanaka_ja_97") (:content . "Tanaka Corpus Ja Set 97"))
  ((:path . "tanaka_ja_98") (:content . "Tanaka Corpus Ja Set 98"))
  ((:path . "tanaka_ja_99") (:content . "Tanaka Corpus Ja Set 99"))
)
