;;;
;;; this file should be `Index.lisp' and reside in the directory containing the
;;; tsdb(1) test suite skeleton databases (typically a subdirectory `skeletons'
;;; in the tsdb(1) database root directory `*tsdb-home*').

(
  ((:path . "tc-000") (:content . "Tanaka Corpus Ja Set 0 (dev)"))
  ((:path . "tc-001") (:content . "Tanaka Corpus Ja Set 1 (dev)"))
  ((:path . "tc-002") (:content . "Tanaka Corpus Ja Set 2 (dev)"))
  ((:path . "tc-003") (:content . "Tanaka Corpus Ja Set 3 (test)"))
  ((:path . "tc-004") (:content . "Tanaka Corpus Ja Set 4 (test)"))
  ((:path . "tc-005") (:content . "Tanaka Corpus Ja Set 5 (test)"))
  ((:path . "tc-006") (:content . "Tanaka Corpus Ja Set 6"))
  ((:path . "tc-007") (:content . "Tanaka Corpus Ja Set 7"))
  ((:path . "tc-008") (:content . "Tanaka Corpus Ja Set 8"))
  ((:path . "tc-009") (:content . "Tanaka Corpus Ja Set 9"))
  ((:path . "tc-010") (:content . "Tanaka Corpus Ja Set 10"))
  ((:path . "tc-011") (:content . "Tanaka Corpus Ja Set 11"))
  ((:path . "tc-012") (:content . "Tanaka Corpus Ja Set 12"))
  ((:path . "tc-013") (:content . "Tanaka Corpus Ja Set 13"))
  ((:path . "tc-014") (:content . "Tanaka Corpus Ja Set 14"))
  ((:path . "tc-015") (:content . "Tanaka Corpus Ja Set 15"))
  ((:path . "tc-016") (:content . "Tanaka Corpus Ja Set 16"))
  ((:path . "tc-017") (:content . "Tanaka Corpus Ja Set 17"))
  ((:path . "tc-018") (:content . "Tanaka Corpus Ja Set 18"))
  ((:path . "tc-019") (:content . "Tanaka Corpus Ja Set 19"))
  ((:path . "tc-020") (:content . "Tanaka Corpus Ja Set 20"))
  ((:path . "tc-021") (:content . "Tanaka Corpus Ja Set 21"))
  ((:path . "tc-022") (:content . "Tanaka Corpus Ja Set 22"))
  ((:path . "tc-023") (:content . "Tanaka Corpus Ja Set 23"))
  ((:path . "tc-024") (:content . "Tanaka Corpus Ja Set 24"))
  ((:path . "tc-025") (:content . "Tanaka Corpus Ja Set 25"))
  ((:path . "tc-026") (:content . "Tanaka Corpus Ja Set 26"))
  ((:path . "tc-027") (:content . "Tanaka Corpus Ja Set 27"))
  ((:path . "tc-028") (:content . "Tanaka Corpus Ja Set 28"))
  ((:path . "tc-029") (:content . "Tanaka Corpus Ja Set 29"))
  ((:path . "tc-030") (:content . "Tanaka Corpus Ja Set 30"))
  ((:path . "tc-031") (:content . "Tanaka Corpus Ja Set 31"))
  ((:path . "tc-032") (:content . "Tanaka Corpus Ja Set 32"))
  ((:path . "tc-033") (:content . "Tanaka Corpus Ja Set 33"))
  ((:path . "tc-034") (:content . "Tanaka Corpus Ja Set 34"))
  ((:path . "tc-035") (:content . "Tanaka Corpus Ja Set 35"))
  ((:path . "tc-036") (:content . "Tanaka Corpus Ja Set 36"))
  ((:path . "tc-037") (:content . "Tanaka Corpus Ja Set 37"))
  ((:path . "tc-038") (:content . "Tanaka Corpus Ja Set 38"))
  ((:path . "tc-039") (:content . "Tanaka Corpus Ja Set 39"))
  ((:path . "tc-040") (:content . "Tanaka Corpus Ja Set 40"))
  ((:path . "tc-041") (:content . "Tanaka Corpus Ja Set 41"))
  ((:path . "tc-042") (:content . "Tanaka Corpus Ja Set 42"))
  ((:path . "tc-043") (:content . "Tanaka Corpus Ja Set 43"))
  ((:path . "tc-044") (:content . "Tanaka Corpus Ja Set 44"))
  ((:path . "tc-045") (:content . "Tanaka Corpus Ja Set 45"))
  ((:path . "tc-046") (:content . "Tanaka Corpus Ja Set 46"))
  ((:path . "tc-047") (:content . "Tanaka Corpus Ja Set 47"))
  ((:path . "tc-048") (:content . "Tanaka Corpus Ja Set 48"))
  ((:path . "tc-049") (:content . "Tanaka Corpus Ja Set 49"))
  ((:path . "tc-050") (:content . "Tanaka Corpus Ja Set 50"))
  ((:path . "tc-051") (:content . "Tanaka Corpus Ja Set 51"))
  ((:path . "tc-052") (:content . "Tanaka Corpus Ja Set 52"))
  ((:path . "tc-053") (:content . "Tanaka Corpus Ja Set 53"))
  ((:path . "tc-054") (:content . "Tanaka Corpus Ja Set 54"))
  ((:path . "tc-055") (:content . "Tanaka Corpus Ja Set 55"))
  ((:path . "tc-056") (:content . "Tanaka Corpus Ja Set 56"))
  ((:path . "tc-057") (:content . "Tanaka Corpus Ja Set 57"))
  ((:path . "tc-058") (:content . "Tanaka Corpus Ja Set 58"))
  ((:path . "tc-059") (:content . "Tanaka Corpus Ja Set 59"))
  ((:path . "tc-060") (:content . "Tanaka Corpus Ja Set 60"))
  ((:path . "tc-061") (:content . "Tanaka Corpus Ja Set 61"))
  ((:path . "tc-062") (:content . "Tanaka Corpus Ja Set 62"))
  ((:path . "tc-063") (:content . "Tanaka Corpus Ja Set 63"))
  ((:path . "tc-064") (:content . "Tanaka Corpus Ja Set 64"))
  ((:path . "tc-065") (:content . "Tanaka Corpus Ja Set 65"))
  ((:path . "tc-066") (:content . "Tanaka Corpus Ja Set 66"))
  ((:path . "tc-067") (:content . "Tanaka Corpus Ja Set 67"))
  ((:path . "tc-068") (:content . "Tanaka Corpus Ja Set 68"))
  ((:path . "tc-069") (:content . "Tanaka Corpus Ja Set 69"))
  ((:path . "tc-070") (:content . "Tanaka Corpus Ja Set 70"))
  ((:path . "tc-071") (:content . "Tanaka Corpus Ja Set 71"))
  ((:path . "tc-072") (:content . "Tanaka Corpus Ja Set 72"))
  ((:path . "tc-073") (:content . "Tanaka Corpus Ja Set 73"))
  ((:path . "tc-074") (:content . "Tanaka Corpus Ja Set 74"))
  ((:path . "tc-075") (:content . "Tanaka Corpus Ja Set 75"))
  ((:path . "tc-076") (:content . "Tanaka Corpus Ja Set 76"))
  ((:path . "tc-077") (:content . "Tanaka Corpus Ja Set 77"))
  ((:path . "tc-078") (:content . "Tanaka Corpus Ja Set 78"))
  ((:path . "tc-079") (:content . "Tanaka Corpus Ja Set 79"))
  ((:path . "tc-080") (:content . "Tanaka Corpus Ja Set 80"))
  ((:path . "tc-081") (:content . "Tanaka Corpus Ja Set 81"))
  ((:path . "tc-082") (:content . "Tanaka Corpus Ja Set 82"))
  ((:path . "tc-083") (:content . "Tanaka Corpus Ja Set 83"))
  ((:path . "tc-084") (:content . "Tanaka Corpus Ja Set 84"))
  ((:path . "tc-085") (:content . "Tanaka Corpus Ja Set 85"))
  ((:path . "tc-086") (:content . "Tanaka Corpus Ja Set 86"))
  ((:path . "tc-087") (:content . "Tanaka Corpus Ja Set 87"))
  ((:path . "tc-088") (:content . "Tanaka Corpus Ja Set 88"))
  ((:path . "tc-089") (:content . "Tanaka Corpus Ja Set 89"))
  ((:path . "tc-090") (:content . "Tanaka Corpus Ja Set 90"))
  ((:path . "tc-091") (:content . "Tanaka Corpus Ja Set 91"))
  ((:path . "tc-092") (:content . "Tanaka Corpus Ja Set 92"))
  ((:path . "tc-093") (:content . "Tanaka Corpus Ja Set 93"))
  ((:path . "tc-094") (:content . "Tanaka Corpus Ja Set 94"))
  ((:path . "tc-095") (:content . "Tanaka Corpus Ja Set 95"))
  ((:path . "tc-096") (:content . "Tanaka Corpus Ja Set 96"))
  ((:path . "tc-097") (:content . "Tanaka Corpus Ja Set 97"))
  ((:path . "tc-098") (:content . "Tanaka Corpus Ja Set 98"))
  ((:path . "tc-099") (:content . "Tanaka Corpus Ja Set 99"))
  ((:path . "tc-100") (:content . "Tanaka Corpus Ja Set 100"))
)
